spring.application.name=toolmgmt
#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/htm_dblotus3
spring.datasource.username=root
spring.datasource.password=26082003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
###
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

###
#config jwt
lotusgroup.jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
lotusgroup.jwt.access-token-validity-in-seconds=8640000
lotusgroup.jwt.refresh-token-validity-in-seconds=8640000
#
###

#config upload file
###
#default = 1MB
spring.servlet.multipart.max-file-size=50MB

#default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB

#base path
lotusgroup.upload-file.dir=file:///D:/LAP_TRINH_A_Z/UDEMY/Java/JobHunter/upload/
lotusgroup.upload-file.public-url=/uploads
###

###
#config pagination
#start page = 1
spring.data.web.pageable.one-indexed-parameters=true



# CẤU HÌNH CHẠY Ở SERVER
server.address=0.0.0.0